export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const APP_VERSION = 'APP_VERSION';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_INFO = 'FORGOT_PASSWORD_INFO';
export const OTP_MODAL = "OTP_MODAL";
export const ONE_SIGNAL_ROUTE = "ONE_SIGNAL_ROUTE";

export const STUDENT_CHANGED = 'STUDENT_CHANGED';
export const CLASS_CHANGED = 'CLASS_CHANGED';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';


export const GET_ACTIVITY = "GET_ACTIVITY";
export const GET_STUDENTS = "GET_STUDENTS";
export const SAVE_ACTIVITY = "SAVE_ACTIVITY";
export const GET_NOTICE = "GET_ACTIVITY";
export const GET_HOMEWORK = "GET_HOMEWORK";

export const GET_LEAVES_REQUEST = "GET_LEAVES_REQUEST";
export const SAVE_LEAVES_REQUEST = "SAVE_LEAVES_REQUEST";

export const SET_FEE_PAYMENT_INFO = "SET_FEE_PAYMENT_INFO";

export const GET_DASHBOARD_MENU = "GET_DASHBOARD_MENU";
export const GET_SUB_DASHBOARD_MENU = "GET_SUB_DASHBOARD_MENU";
export const SET_DASHBOARD_ID = "SET_DASHBOARD_ID";